In [ ]:
import pandas as pd

In [ ]:
pd.reset_option('display.max_rows')

In [ ]:
#pd.set_option('display.max_rows', None)

In [ ]:
df = pd.read_excel('cosing_clean.xlsx')
df.drop('Unnamed: 0', inplace=True, axis=1)

In [ ]:
df.shape

(3617, 18)

18 Columns, 3617 rows

In [ ]:
df.isna().sum()

Functionality          0
Canonical_smiles       0
Chemical Name          0
Smiles                 0
Functionality.1        0
Functionality 0        0
Functionality 1     1894
Functionality 2     2911
Functionality 3     3353
Functionality 4     3518
Functionality 5     3579
Functionality 6     3609
Functionality 7     3616
Functionality 8     3617
Functionality 9     3617
Functionality 10    3617
Functionality 11    3617
Functionality 12    3617
dtype: int64

Functionality 8 to Functionality 12 consists of only null values, hence dropping them

In [ ]:
df.drop(['Functionality 8','Functionality 9','Functionality 10','Functionality 11','Functionality 12'], inplace=True, axis=1)

In [ ]:
df.head()

,Functionality,Canonical_smiles,Chemical Name,Smiles,Functionality.1,Functionality 0,Functionality 1,Functionality 2,Functionality 3,Functionality 4,Functionality 5,Functionality 6,Functionality 7
0,emulsionstabilising,CC(C)C1=CC2=CCC3C(C)(C(=O)O)CCCC3(C)C2CC1,ABIETIC ACID,CC(C)C1=CC2=CCC3C(C2CC1)(CCCC3(C)C(=O)O)C,Emulsion stabilising,Emulsion stabilising,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,viscositycontrolling,CC(C)C1=CC2=CCC3C(C)(CO)CCCC3(C)C2CC1,ABIETYL ALCOHOL,CC(C)C1=CC2=CCC3C(CCCC3(C2CC1)C)(C)CO,Viscosity controlling,Viscosity controlling,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,nailconditioning,CC=O,ACETALDEHYDE,CC=O,Nail conditioning,Nail conditioning,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"antistatic,humectant",CC(=O)NCCO,ACETAMIDE MEA,CC(=O)NCCO,Antistatic/humectant,Antistatic,humectant,NaN,NaN,NaN,NaN,NaN,NaN
4,"antistatic,emollient,hairconditioning",CC(=O)NCCOCCCC[N+](C)(C)C.[Cl-],ACETAMIDOETHOXYBUTYL TRIMONIUM CHLORIDE,CC(=O)NCCOCCCC[N+](C)(C)C.[Cl-],Antistatic/emollient/hair conditioning,Antistatic,emollient,hair conditioning,NaN,NaN,NaN,NaN,NaN

In [ ]:
df[['Functionality','Functionality.1']]

,Functionality,Functionality.1
0,emulsionstabilising,Emulsion stabilising
1,viscositycontrolling,Viscosity controlling
2,nailconditioning,Nail conditioning
3,"antistatic,humectant",Antistatic/humectant
4,"antistatic,emollient,hairconditioning",Antistatic/emollient/hair conditioning
...,...,...
3612,"surfactant,foaming,cleansing",Surfactant/foaming/cleansing
3613,"surfactant,foaming,cleansing",Surfactant/foaming/cleansing
3614,"surfactant,cleansing,foaming",Surfactant/cleansing/foaming
3615,"antistatic,surfactant,foaming,cleansing",Antistatic/surfactant/foaming/cleansing
3616,chelating,Chelating

Functionality.1 is cleaned version of Functionalisty, so we can drop Functionality

In [ ]:
df.drop('Functionality', axis=1, inplace=True)

In [ ]:
df.head()

,Canonical_smiles,Chemical Name,Smiles,Functionality.1,Functionality 0,Functionality 1,Functionality 2,Functionality 3,Functionality 4,Functionality 5,Functionality 6,Functionality 7
0,CC(C)C1=CC2=CCC3C(C)(C(=O)O)CCCC3(C)C2CC1,ABIETIC ACID,CC(C)C1=CC2=CCC3C(C2CC1)(CCCC3(C)C(=O)O)C,Emulsion stabilising,Emulsion stabilising,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CC(C)C1=CC2=CCC3C(C)(CO)CCCC3(C)C2CC1,ABIETYL ALCOHOL,CC(C)C1=CC2=CCC3C(CCCC3(C2CC1)C)(C)CO,Viscosity controlling,Viscosity controlling,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CC=O,ACETALDEHYDE,CC=O,Nail conditioning,Nail conditioning,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CC(=O)NCCO,ACETAMIDE MEA,CC(=O)NCCO,Antistatic/humectant,Antistatic,humectant,NaN,NaN,NaN,NaN,NaN,NaN
4,CC(=O)NCCOCCCC[N+](C)(C)C.[Cl-],ACETAMIDOETHOXYBUTYL TRIMONIUM CHLORIDE,CC(=O)NCCOCCCC[N+](C)(C)C.[Cl-],Antistatic/emollient/hair conditioning,Antistatic,emollient,hair conditioning,NaN,NaN,NaN,NaN,NaN

In [ ]:
print(df.nunique(axis=0))

Canonical_smiles    2962
Chemical Name       3256
Smiles              2962
Functionality.1      689
Functionality 0       96
Functionality 1       62
Functionality 2       50
Functionality 3       37
Functionality 4       26
Functionality 5       15
Functionality 6        6
Functionality 7        1
dtype: int64

In [ ]:
df[['Canonical_smiles','Smiles']]

,Canonical_smiles,Smiles
0,CC(C)C1=CC2=CCC3C(C)(C(=O)O)CCCC3(C)C2CC1,CC(C)C1=CC2=CCC3C(C2CC1)(CCCC3(C)C(=O)O)C
1,CC(C)C1=CC2=CCC3C(C)(CO)CCCC3(C)C2CC1,CC(C)C1=CC2=CCC3C(CCCC3(C2CC1)C)(C)CO
2,CC=O,CC=O
3,CC(=O)NCCO,CC(=O)NCCO
4,CC(=O)NCCOCCCC[N+](C)(C)C.[Cl-],CC(=O)NCCOCCCC[N+](C)(C)C.[Cl-]
...,...,...
3612,CCCCCCCCCCCCOCCOS(=O)(=O)O.N,CCCCCCCCCCCCOCCOS(=O)(=O)O.N
3613,CCCCCCCCCCCCOCCOS(=O)(=O)O.N,CCCCCCCCCCCCOCCOS(=O)(=O)O.N
3614,CCCCCCCCCCCCOCCOS(=O)(=O)O.N,CCCCCCCCCCCCOCCOS(=O)(=O)O.N
3615,CCCCCCCCCCCC(=O)N(C)CC(=O)O.N,CCCCCCCCCCCC(=O)N(C)CC(=O)O.N
3616,O=C(O)CCN(CC(=O)O)CC(=O)O,C(CN(CC(=O)O)CC(=O)O)C(=O)O

Should we keep SMiles and Canonical_Smailes both?

In [ ]:
df['Chemical Name']

0                                  ABIETIC ACID
1                               ABIETYL ALCOHOL
2                                  ACETALDEHYDE
3                                 ACETAMIDE MEA
4       ACETAMIDOETHOXYBUTYL TRIMONIUM CHLORIDE
                         ...
3612                 AMMONIUM LAURETH-7 SULFATE
3613                 AMMONIUM LAURETH-9 SULFATE
3614                AMMONIUM LAURETH-12 SULFATE
3615               AMMONIUM LAUROYL SARCOSINATE
3616                 BETA-ALANINE DIACETIC ACID
Name: Chemical Name, Length: 3617, dtype: object

In [ ]:
df[df.duplicated(keep='first')]

,Canonical_smiles,Chemical Name,Smiles,Functionality.1,Functionality 0,Functionality 1,Functionality 2,Functionality 3,Functionality 4,Functionality 5,Functionality 6,Functionality 7
70,OCC1OC(OC2C3COC2C(O)C(OC2C(O)C(CO)OC(OC4C5COC4...,AGAROSE,C1C2C(C(O1)C(C(O2)O)O)OC3C(C(C(C(O3)CO)O)OC4C(...,Skin conditioning/viscosity controlling,Skin conditioning,viscosity controlling,NaN,NaN,NaN,NaN,NaN,NaN
72,CC(N)C(=O)O,ALANINE,CC(C(=O)O)N,Antistatic,Antistatic,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,CC(N)C(=O)O,ALANINE,CC(C(=O)O)N,Antistatic,Antistatic,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,O=C(O)CCCCCCCC(O)C(O)CCCCCCO,ALEURITIC ACID,C(CCCC(C(CCCCCCO)O)O)CCCC(=O)O,Skin conditioning,Skin conditioning,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,O=C(O)CCCCCCCC(O)C(O)CCCCCCO,ALEURITIC ACID,C(CCCC(C(CCCCCCO)O)O)CCCC(=O)O,Skin conditioning,Skin conditioning,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
3535,NC(Cc1c[nH]c2ccccc12)C(=O)O,TRYPTOPHAN,C1=CC=C2C(=C1)C(=CN2)CC(C(=O)O)N,Antistatic,Antistatic,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3538,COC1=C(OC)C(=O)C(CC=C(C)CCC=C(C)CCC=C(C)CCC=C(...,UBIQUINONE,CC1=C(C(=O)C(=C(C1=O)OC)OC)CC=C(C)CCC=C(C)CCC=...,Antioxidant/skin conditioning,Antioxidant,skin conditioning,NaN,NaN,NaN,NaN,NaN,NaN
3559,Cc1cc(Cl)cc2c1C(=O)C(=C1Sc3cc(Cl)cc(C)c3C1=O)S2,VAT RED 1,CC1=CC(=CC2=C1C(=O)C(=C3C(=O)C4=C(S3)C=C(C=C4C...,Hair dyeing,Hair dyeing,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3588,[O-][n+]1ccccc1[S-].[O-][n+]1ccccc1[S-].[Zn+2],ZINC PYRITHIONE,C1=CC=[N+](C(=C1)[S-])[O-].C1=CC=[N+](C(=C1)[S...,Preservative/antiseborrhoeic,Preservative,antiseborrhoeic,NaN,NaN,NaN,NaN,NaN,NaN
3598,C=CCCCCCCCCC(=O)O.C=CCCCCCCCCC(=O)O.[Zn],ZINC UNDECYLENATE,C=CCCCCCCCCC(=O)O.C=CCCCCCCCCC(=O)O.[Zn],Antimicrobial/opacifying,Antimicrobial,opacifying,NaN,NaN,NaN,NaN,NaN,NaN

241 rows are duplicated, so we'll drop them

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df[df.duplicated(keep='first')]

Empty DataFrame
Columns: [Canonical_smiles, Chemical Name, Smiles, Functionality.1, Functionality 0, Functionality 1, Functionality 2, Functionality 3, Functionality 4, Functionality 5, Functionality 6, Functionality 7]
Index: []

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3376 entries, 0 to 3616
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Canonical_smiles  3376 non-null   object
 1   Chemical Name     3376 non-null   object
 2   Smiles            3376 non-null   object
 3   Functionality.1   3376 non-null   object
 4   Functionality 0   3376 non-null   object
 5   Functionality 1   1609 non-null   object
 6   Functionality 2   679 non-null    object
 7   Functionality 3   261 non-null    object
 8   Functionality 4   99 non-null     object
 9   Functionality 5   38 non-null     object
 10  Functionality 6   8 non-null      object
 11  Functionality 7   1 non-null      object
dtypes: object(12)
memory usage: 342.9+ KB

In [ ]:
df.head(2)

,Canonical_smiles,Chemical Name,Smiles,Functionality.1,Functionality 0,Functionality 1,Functionality 2,Functionality 3,Functionality 4,Functionality 5,Functionality 6,Functionality 7
0,CC(C)C1=CC2=CCC3C(C)(C(=O)O)CCCC3(C)C2CC1,ABIETIC ACID,CC(C)C1=CC2=CCC3C(C2CC1)(CCCC3(C)C(=O)O)C,Emulsion stabilising,Emulsion stabilising,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CC(C)C1=CC2=CCC3C(C)(CO)CCCC3(C)C2CC1,ABIETYL ALCOHOL,CC(C)C1=CC2=CCC3C(CCCC3(C2CC1)C)(C)CO,Viscosity controlling,Viscosity controlling,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df['Chemical Name']

0                                  ABIETIC ACID
1                               ABIETYL ALCOHOL
2                                  ACETALDEHYDE
3                                 ACETAMIDE MEA
4       ACETAMIDOETHOXYBUTYL TRIMONIUM CHLORIDE
                         ...
3612                 AMMONIUM LAURETH-7 SULFATE
3613                 AMMONIUM LAURETH-9 SULFATE
3614                AMMONIUM LAURETH-12 SULFATE
3615               AMMONIUM LAUROYL SARCOSINATE
3616                 BETA-ALANINE DIACETIC ACID
Name: Chemical Name, Length: 3376, dtype: object

In [ ]:
#df['Chemical Name'].to_frame(name='column_name').to_excel('Ingred.xlsx', sheet_name='Step-1')

Further Cleaning required!

In [ ]:
df.drop('Smiles',axis=1, inplace=True)

In [ ]:
df.shape

(3376, 11)

In [ ]:
df

,Canonical_smiles,Chemical Name,Functionality.1,Functionality 0,Functionality 1,Functionality 2,Functionality 3,Functionality 4,Functionality 5,Functionality 6,Functionality 7
0,CC(C)C1=CC2=CCC3C(C)(C(=O)O)CCCC3(C)C2CC1,ABIETIC ACID,Emulsion stabilising,Emulsion stabilising,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CC(C)C1=CC2=CCC3C(C)(CO)CCCC3(C)C2CC1,ABIETYL ALCOHOL,Viscosity controlling,Viscosity controlling,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CC=O,ACETALDEHYDE,Nail conditioning,Nail conditioning,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CC(=O)NCCO,ACETAMIDE MEA,Antistatic/humectant,Antistatic,humectant,NaN,NaN,NaN,NaN,NaN,NaN
4,CC(=O)NCCOCCCC[N+](C)(C)C.[Cl-],ACETAMIDOETHOXYBUTYL TRIMONIUM CHLORIDE,Antistatic/emollient/hair conditioning,Antistatic,emollient,hair conditioning,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
3612,CCCCCCCCCCCCOCCOS(=O)(=O)O.N,AMMONIUM LAURETH-7 SULFATE,Surfactant/foaming/cleansing,Surfactant,foaming,cleansing,NaN,NaN,NaN,NaN,NaN
3613,CCCCCCCCCCCCOCCOS(=O)(=O)O.N,AMMONIUM LAURETH-9 SULFATE,Surfactant/foaming/cleansing,Surfactant,foaming,cleansing,NaN,NaN,NaN,NaN,NaN
3614,CCCCCCCCCCCCOCCOS(=O)(=O)O.N,AMMONIUM LAURETH-12 SULFATE,Surfactant/cleansing/foaming,Surfactant,cleansing,foaming,NaN,NaN,NaN,NaN,NaN
3615,CCCCCCCCCCCC(=O)N(C)CC(=O)O.N,AMMONIUM LAUROYL SARCOSINATE,Antistatic/surfactant/foaming/cleansing,Antistatic,surfactant,foaming,cleansing,NaN,NaN,NaN,NaN
3616,O=C(O)CCN(CC(=O)O)CC(=O)O,BETA-ALANINE DIACETIC ACID,Chelating,Chelating,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.head()

,Canonical_smiles,Chemical Name,Functionality.1,Functionality 0,Functionality 1,Functionality 2,Functionality 3,Functionality 4,Functionality 5,Functionality 6,Functionality 7
0,CC(C)C1=CC2=CCC3C(C)(C(=O)O)CCCC3(C)C2CC1,ABIETIC ACID,Emulsion stabilising,Emulsion stabilising,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CC(C)C1=CC2=CCC3C(C)(CO)CCCC3(C)C2CC1,ABIETYL ALCOHOL,Viscosity controlling,Viscosity controlling,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CC=O,ACETALDEHYDE,Nail conditioning,Nail conditioning,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CC(=O)NCCO,ACETAMIDE MEA,Antistatic/humectant,Antistatic,humectant,NaN,NaN,NaN,NaN,NaN,NaN
4,CC(=O)NCCOCCCC[N+](C)(C)C.[Cl-],ACETAMIDOETHOXYBUTYL TRIMONIUM CHLORIDE,Antistatic/emollient/hair conditioning,Antistatic,emollient,hair conditioning,NaN,NaN,NaN,NaN,NaN

In [ ]:
chem_name=df[['Canonical_smiles','Chemical Name']]
chem_name

,Canonical_smiles,Chemical Name
0,CC(C)C1=CC2=CCC3C(C)(C(=O)O)CCCC3(C)C2CC1,ABIETIC ACID
1,CC(C)C1=CC2=CCC3C(C)(CO)CCCC3(C)C2CC1,ABIETYL ALCOHOL
2,CC=O,ACETALDEHYDE
3,CC(=O)NCCO,ACETAMIDE MEA
4,CC(=O)NCCOCCCC[N+](C)(C)C.[Cl-],ACETAMIDOETHOXYBUTYL TRIMONIUM CHLORIDE
...,...,...
3612,CCCCCCCCCCCCOCCOS(=O)(=O)O.N,AMMONIUM LAURETH-7 SULFATE
3613,CCCCCCCCCCCCOCCOS(=O)(=O)O.N,AMMONIUM LAURETH-9 SULFATE
3614,CCCCCCCCCCCCOCCOS(=O)(=O)O.N,AMMONIUM LAURETH-12 SULFATE
3615,CCCCCCCCCCCC(=O)N(C)CC(=O)O.N,AMMONIUM LAUROYL SARCOSINATE
3616,O=C(O)CCN(CC(=O)O)CC(=O)O,BETA-ALANINE DIACETIC ACID

In [ ]:
df[['Canonical_smiles','Chemical Name']][df['Chemical Name'].duplicated(keep='first')]

                                       Canonical_smiles      Chemical Name
24    CCN(CC)c1ccc(C(=C2C=CC(=[N+](CC)CC)C=C2)c2cc([...        ACID BLUE 3
25    CCN(CC)c1ccc(C(=C2C=CC(=[N+](CC)CC)C=C2)c2cc(O...        ACID BLUE 3
27    CCN(Cc1cccc(S(=O)(=O)[O-])c1)c1ccc(C(=C2C=CC(=...        ACID BLUE 9
28    CCN(Cc1cccc(S(=O)(=O)O)c1)c1ccc(C(=C2C=CC(=[N+...        ACID BLUE 9
29    CCN(Cc1cccc(S(=O)(=O)[O-])c1)c1ccc(C(=C2C=CC(=...        ACID BLUE 9
...                                                 ...                ...
3587                                   On1ccccc1=S.[Zn]    ZINC PYRITHIONE
3589               On1ccccc1=S.[O-][n+]1ccccc1[S-].[Zn]    ZINC PYRITHIONE
3595           C=CCCCCCCCCC(=O)O.C=CCCCCCCCCC(=O)O.[Zn]  ZINC UNDECYLENATE
3596                           C=CCCCCCCCCC(=O)O.[Zn+2]  ZINC UNDECYLENATE
3597                               C=CCCCCCCCCC(=O)[O-]  ZINC UNDECYLENATE

[120 rows x 2 columns]

In [ ]:
Chem_Name_1= chem_name.drop_duplicates(subset='Chemical Name',inplace=False,keep='first') 
Chem_Name_1 #unique values based on chemical name

,Canonical_smiles,Chemical Name
0,CC(C)C1=CC2=CCC3C(C)(C(=O)O)CCCC3(C)C2CC1,ABIETIC ACID
1,CC(C)C1=CC2=CCC3C(C)(CO)CCCC3(C)C2CC1,ABIETYL ALCOHOL
2,CC=O,ACETALDEHYDE
3,CC(=O)NCCO,ACETAMIDE MEA
4,CC(=O)NCCOCCCC[N+](C)(C)C.[Cl-],ACETAMIDOETHOXYBUTYL TRIMONIUM CHLORIDE
...,...,...
3612,CCCCCCCCCCCCOCCOS(=O)(=O)O.N,AMMONIUM LAURETH-7 SULFATE
3613,CCCCCCCCCCCCOCCOS(=O)(=O)O.N,AMMONIUM LAURETH-9 SULFATE
3614,CCCCCCCCCCCCOCCOS(=O)(=O)O.N,AMMONIUM LAURETH-12 SULFATE
3615,CCCCCCCCCCCC(=O)N(C)CC(=O)O.N,AMMONIUM LAUROYL SARCOSINATE
3616,O=C(O)CCN(CC(=O)O)CC(=O)O,BETA-ALANINE DIACETIC ACID

In [ ]:
df[['Canonical_smiles','Chemical Name']][df['Canonical_smiles'].duplicated(keep=False)]

,Canonical_smiles,Chemical Name
20,Nc1c(N=Nc2ccc([N+](=O)[O-])cc2)c(S(=O)(=O)[O-]...,ACID BLACK 1
23,CCN(CC)c1ccc(C(=C2C=CC(=[N+](CC)CC)C=C2)c2cc(O...,ACID BLUE 3
26,CCN(Cc1cccc(S(=O)(=O)[O-])c1)c1ccc(C(=C2C=CC(=...,ACID BLUE 9
31,O=C1C(c2[nH]c3ccc(S(=O)(=O)[O-])cc3c2O)=Nc2ccc...,ACID BLUE 74
34,Cc1ccc(Nc2ccc(Nc3ccc(C)cc3S(=O)(=O)[O-])c3c2C(...,ACID GREEN 25
...,...,...
3610,CCCCCCCCCCCCOCCOS(=O)(=O)O.N,AMMONIUM LAURETH SULFATE
3611,CCCCCCCCCCCCOCCOS(=O)(=O)O.N,AMMONIUM LAURETH-5 SULFATE
3612,CCCCCCCCCCCCOCCOS(=O)(=O)O.N,AMMONIUM LAURETH-7 SULFATE
3613,CCCCCCCCCCCCOCCOS(=O)(=O)O.N,AMMONIUM LAURETH-9 SULFATE
3614,CCCCCCCCCCCCOCCOS(=O)(=O)O.N,AMMONIUM LAURETH-12 SULFATE

In [ ]:
Chem_Name_2= chem_name.drop_duplicates(subset='Canonical_smiles',inplace=False,keep='first') 
Chem_Name_2 #unique values based on Canonical_smiles

,Canonical_smiles,Chemical Name
0,CC(C)C1=CC2=CCC3C(C)(C(=O)O)CCCC3(C)C2CC1,ABIETIC ACID
1,CC(C)C1=CC2=CCC3C(C)(CO)CCCC3(C)C2CC1,ABIETYL ALCOHOL
2,CC=O,ACETALDEHYDE
3,CC(=O)NCCO,ACETAMIDE MEA
4,CC(=O)NCCOCCCC[N+](C)(C)C.[Cl-],ACETAMIDOETHOXYBUTYL TRIMONIUM CHLORIDE
...,...,...
3608,Nc1ncnc2c1ncn2C1OC2COP(=O)(O)OC2C1O,ADENOSINE CYCLIC PHOSPHATE
3609,CCCCCCCCCCCCCCCCOP(=O)([O-])OCCCCCCCCCCCCCCCC....,ALUMINUM DICETYL PHOSPHATE
3610,CCCCCCCCCCCCOCCOS(=O)(=O)O.N,AMMONIUM LAURETH SULFATE
3615,CCCCCCCCCCCC(=O)N(C)CC(=O)O.N,AMMONIUM LAUROYL SARCOSINATE
3616,O=C(O)CCN(CC(=O)O)CC(=O)O,BETA-ALANINE DIACETIC ACID

In [ ]:
with pd.ExcelWriter("Ingred_v2.xlsx") as writer:
  Chem_Name_1['Chemical Name'].to_excel(writer, 
                                        sheet_name='Unique chemical name',
                                        index=False)
  Chem_Name_2['Chemical Name'].to_excel(writer, 
                                        sheet_name='Unique Canonical_smiles',
                                        index=False)

In [ ]:
df[df['Chemical Name'].duplicated(keep=False)]

,Canonical_smiles,Chemical Name,Functionality.1,Functionality 0,Functionality 1,Functionality 2,Functionality 3,Functionality 4,Functionality 5,Functionality 6,Functionality 7
23,CCN(CC)c1ccc(C(=C2C=CC(=[N+](CC)CC)C=C2)c2cc(O...,ACID BLUE 3,Hair dyeing,Hair dyeing,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,CCN(CC)c1ccc(C(=C2C=CC(=[N+](CC)CC)C=C2)c2cc([...,ACID BLUE 3,Hair dyeing,Hair dyeing,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,CCN(CC)c1ccc(C(=C2C=CC(=[N+](CC)CC)C=C2)c2cc(O...,ACID BLUE 3,Hair dyeing,Hair dyeing,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,CCN(Cc1cccc(S(=O)(=O)[O-])c1)c1ccc(C(=C2C=CC(=...,ACID BLUE 9,Hair dyeing,Hair dyeing,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,CCN(Cc1cccc(S(=O)(=O)[O-])c1)c1ccc(C(=C2C=CC(=...,ACID BLUE 9,Hair dyeing,Hair dyeing,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
3589,On1ccccc1=S.[O-][n+]1ccccc1[S-].[Zn],ZINC PYRITHIONE,Preservative/antiseborrhoeic,Preservative,antiseborrhoeic,NaN,NaN,NaN,NaN,NaN,NaN
3594,C=CCCCCCCCCC(=O)[O-].C=CCCCCCCCCC(=O)[O-].[Zn+2],ZINC UNDECYLENATE,Antimicrobial/opacifying,Antimicrobial,opacifying,NaN,NaN,NaN,NaN,NaN,NaN
3595,C=CCCCCCCCCC(=O)O.C=CCCCCCCCCC(=O)O.[Zn],ZINC UNDECYLENATE,Antimicrobial/opacifying,Antimicrobial,opacifying,NaN,NaN,NaN,NaN,NaN,NaN
3596,C=CCCCCCCCCC(=O)O.[Zn+2],ZINC UNDECYLENATE,Antimicrobial/opacifying,Antimicrobial,opacifying,NaN,NaN,NaN,NaN,NaN,NaN
3597,C=CCCCCCCCCC(=O)[O-],ZINC UNDECYLENATE,Antimicrobial/opacifying,Antimicrobial,opacifying,NaN,NaN,NaN,NaN,NaN,NaN