In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_excel("cosing_clean.xlsx", index_col=0)
df.index = df.index.astype(int)
df.head()

,Functionality,Canonical_smiles,Chemical Name,Smiles,Functionality.1,Functionality 0,Functionality 1,Functionality 2,Functionality 3,Functionality 4,Functionality 5,Functionality 6,Functionality 7,Functionality 8,Functionality 9,Functionality 10,Functionality 11,Functionality 12
0,emulsionstabilising,CC(C)C1=CC2=CCC3C(C)(C(=O)O)CCCC3(C)C2CC1,ABIETIC ACID,CC(C)C1=CC2=CCC3C(C2CC1)(CCCC3(C)C(=O)O)C,Emulsion stabilising,Emulsion stabilising,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,viscositycontrolling,CC(C)C1=CC2=CCC3C(C)(CO)CCCC3(C)C2CC1,ABIETYL ALCOHOL,CC(C)C1=CC2=CCC3C(CCCC3(C2CC1)C)(C)CO,Viscosity controlling,Viscosity controlling,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,nailconditioning,CC=O,ACETALDEHYDE,CC=O,Nail conditioning,Nail conditioning,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"antistatic,humectant",CC(=O)NCCO,ACETAMIDE MEA,CC(=O)NCCO,Antistatic/humectant,Antistatic,humectant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"antistatic,emollient,hairconditioning",CC(=O)NCCOCCCC[N+](C)(C)C.[Cl-],ACETAMIDOETHOXYBUTYL TRIMONIUM CHLORIDE,CC(=O)NCCOCCCC[N+](C)(C)C.[Cl-],Antistatic/emollient/hair conditioning,Antistatic,emollient,hair conditioning,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.isna().sum()

Functionality          0
Canonical_smiles       0
Chemical Name          0
Smiles                 0
Functionality.1        0
Functionality 0        0
Functionality 1     1894
Functionality 2     2911
Functionality 3     3353
Functionality 4     3518
Functionality 5     3579
Functionality 6     3609
Functionality 7     3616
Functionality 8     3617
Functionality 9     3617
Functionality 10    3617
Functionality 11    3617
Functionality 12    3617
dtype: int64

In [5]:
df.duplicated().sum()

241

In [6]:
df = df[df.duplicated() == False]
df.shape

(3376, 18)

In [7]:
print("Duplicate Count")
for col_name in df.columns:
    if not col_name.startswith("Func"):
        print(col_name, ":", df[col_name].duplicated().sum())

Duplicate Count
Canonical_smiles : 414
Chemical Name : 120
Smiles : 414

In [8]:
df[["Canonical_smiles", "Smiles"]].duplicated().sum()

414

In [9]:
df[["Canonical_smiles", "Chemical Name"]].duplicated().sum()

0

In [10]:
df[df["Chemical Name"].duplicated(keep=False)]

,Functionality,Canonical_smiles,Chemical Name,Smiles,Functionality.1,Functionality 0,Functionality 1,Functionality 2,Functionality 3,Functionality 4,Functionality 5,Functionality 6,Functionality 7,Functionality 8,Functionality 9,Functionality 10,Functionality 11,Functionality 12
23,hairdyeing,CCN(CC)c1ccc(C(=C2C=CC(=[N+](CC)CC)C=C2)c2cc(O...,ACID BLUE 3,CCN(CC)C1=CC=C(C=C1)C(=C2C=CC(=[N+](CC)CC)C=C2...,Hair dyeing,Hair dyeing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,hairdyeing,CCN(CC)c1ccc(C(=C2C=CC(=[N+](CC)CC)C=C2)c2cc([...,ACID BLUE 3,[H+].[H+].CCN(CC)C1=CC=C(C=C1)C(=C2C=CC(=[N+](...,Hair dyeing,Hair dyeing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,hairdyeing,CCN(CC)c1ccc(C(=C2C=CC(=[N+](CC)CC)C=C2)c2cc(O...,ACID BLUE 3,CCN(CC)C1=CC=C(C=C1)C(=C2C=CC(=[N+](CC)CC)C=C2...,Hair dyeing,Hair dyeing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,hairdyeing,CCN(Cc1cccc(S(=O)(=O)[O-])c1)c1ccc(C(=C2C=CC(=...,ACID BLUE 9,CCN(CC1=CC(=CC=C1)S(=O)(=O)[O-])C2=CC=C(C=C2)C...,Hair dyeing,Hair dyeing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,hairdyeing,CCN(Cc1cccc(S(=O)(=O)[O-])c1)c1ccc(C(=C2C=CC(=...,ACID BLUE 9,CCN(CC1=CC(=CC=C1)S(=O)(=O)[O-])C2=CC=C(C=C2)C...,Hair dyeing,Hair dyeing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3589,"preservative,antiseborrhoeic",On1ccccc1=S.[O-][n+]1ccccc1[S-].[Zn],ZINC PYRITHIONE,C1=CC=[N+](C(=C1)[S-])[O-].C1=CC(=S)N(C=C1)O.[Zn],Preservative/antiseborrhoeic,Preservative,antiseborrhoeic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3594,"antimicrobial,opacifying",C=CCCCCCCCCC(=O)[O-].C=CCCCCCCCCC(=O)[O-].[Zn+2],ZINC UNDECYLENATE,C=CCCCCCCCCC(=O)[O-].C=CCCCCCCCCC(=O)[O-].[Zn+2],Antimicrobial/opacifying,Antimicrobial,opacifying,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3595,"antimicrobial,opacifying",C=CCCCCCCCCC(=O)O.C=CCCCCCCCCC(=O)O.[Zn],ZINC UNDECYLENATE,C=CCCCCCCCCC(=O)O.C=CCCCCCCCCC(=O)O.[Zn],Antimicrobial/opacifying,Antimicrobial,opacifying,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3596,"antimicrobial,opacifying",C=CCCCCCCCCC(=O)O.[Zn+2],ZINC UNDECYLENATE,C=CCCCCCCCCC(=O)O.[Zn+2],Antimicrobial/opacifying,Antimicrobial,opacifying,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3597,"antimicrobial,opacifying",C=CCCCCCCCCC(=O)[O-],ZINC UNDECYLENATE,C=CCCCCCCCCC(=O)[O-],Antimicrobial/opacifying,Antimicrobial,opacifying,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# df[df["Canonical_smiles"].duplicated(keep=False)]
# for i in (23, 24, 25):
#     print(df.iloc[i]["Canonical_smiles"])
temp = df[df["Chemical Name"].duplicated() == False]
temp["Canonical_smiles"].duplicated(keep=False).sum()
temp
df[df["Canonical_smiles"].duplicated(keep=False)]

,Functionality,Canonical_smiles,Chemical Name,Smiles,Functionality.1,Functionality 0,Functionality 1,Functionality 2,Functionality 3,Functionality 4,Functionality 5,Functionality 6,Functionality 7,Functionality 8,Functionality 9,Functionality 10,Functionality 11,Functionality 12
20,hairdyeing,Nc1c(N=Nc2ccc([N+](=O)[O-])cc2)c(S(=O)(=O)[O-]...,ACID BLACK 1,C1=CC=C(C=C1)N=NC2=C(C3=C(C(=C(C=C3C=C2S(=O)(=...,Hair dyeing,Hair dyeing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,hairdyeing,CCN(CC)c1ccc(C(=C2C=CC(=[N+](CC)CC)C=C2)c2cc(O...,ACID BLUE 3,CCN(CC)C1=CC=C(C=C1)C(=C2C=CC(=[N+](CC)CC)C=C2...,Hair dyeing,Hair dyeing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,hairdyeing,CCN(Cc1cccc(S(=O)(=O)[O-])c1)c1ccc(C(=C2C=CC(=...,ACID BLUE 9,CCN(CC1=CC(=CC=C1)S(=O)(=O)[O-])C2=CC=C(C=C2)C...,Hair dyeing,Hair dyeing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,hairdyeing,O=C1C(c2[nH]c3ccc(S(=O)(=O)[O-])cc3c2O)=Nc2ccc...,ACID BLUE 74,C1=CC2=C(C=C1S(=O)(=O)[O-])C(=C(N2)C3=NC4=C(C3...,Hair dyeing,Hair dyeing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,hairdyeing,Cc1ccc(Nc2ccc(Nc3ccc(C)cc3S(=O)(=O)[O-])c3c2C(...,ACID GREEN 25,CC1=CC(=C(C=C1)NC2=C3C(=C(C=C2)NC4=C(C=C(C=C4)...,Hair dyeing,Hair dyeing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3610,"surfactant,foaming,cleansing",CCCCCCCCCCCCOCCOS(=O)(=O)O.N,AMMONIUM LAURETH SULFATE,CCCCCCCCCCCCOCCOS(=O)(=O)O.N,Surfactant/foaming/cleansing,Surfactant,foaming,cleansing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3611,"surfactant,foaming,cleansing",CCCCCCCCCCCCOCCOS(=O)(=O)O.N,AMMONIUM LAURETH-5 SULFATE,CCCCCCCCCCCCOCCOS(=O)(=O)O.N,Surfactant/foaming/cleansing,Surfactant,foaming,cleansing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3612,"surfactant,foaming,cleansing",CCCCCCCCCCCCOCCOS(=O)(=O)O.N,AMMONIUM LAURETH-7 SULFATE,CCCCCCCCCCCCOCCOS(=O)(=O)O.N,Surfactant/foaming/cleansing,Surfactant,foaming,cleansing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3613,"surfactant,foaming,cleansing",CCCCCCCCCCCCOCCOS(=O)(=O)O.N,AMMONIUM LAURETH-9 SULFATE,CCCCCCCCCCCCOCCOS(=O)(=O)O.N,Surfactant/foaming/cleansing,Surfactant,foaming,cleansing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3614,"surfactant,cleansing,foaming",CCCCCCCCCCCCOCCOS(=O)(=O)O.N,AMMONIUM LAURETH-12 SULFATE,CCCCCCCCCCCCOCCOS(=O)(=O)O.N,Surfactant/cleansing/foaming,Surfactant,cleansing,foaming,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df["Functionality.1"].duplicated(keep="first")

0       False
1       False
2       False
3       False
4       False
        ...
3612     True
3613     True
3614     True
3615     True
3616     True
Name: Functionality.1, Length: 3376, dtype: bool

In [13]:
def remove_duplicate_smiles(df):
    df["alias"] = np.nan
    print(df.isna().sum())
    print(df.shape)
    smiles_table = {}
    for i in range(len(df)):
        cur_row = df.iloc[i]
        smile = cur_row["Smiles"]
        if smile not in smiles_table:
            smiles_table[smile] = i
        else:
            funcs = (col for col in df.columns if col.startswith("Func"))
            first_row = df.iloc[smiles_table[smile]]
            first_row_nan_funcs = (func for func in funcs if pd.isnull(first_row[func]))
            cur_row_notnan_funcs = (func for func in funcs if not pd.isnull(cur_row[func]))
            for func in cur_row_notnan_funcs:
                try:
                    first_row[next(first_row_nan_funcs)] = cur_row[func]
                    df.iloc[smiles_table[smile]] = first_row
                except StopIteration:
                    break
            aliases = "" if pd.isnull(first_row["alias"]) else (first_row["alias"] + "/")
            first_row["alias"] = aliases + cur_row["Chemical Name"]
            df.iloc[smiles_table[smile]] = first_row
    print(df.isna().sum())
    df = df[df["Smiles"].duplicated() == False]
    print(df.shape)
    return df
    
df = remove_duplicate_smiles(df)

Functionality          0
Canonical_smiles       0
Chemical Name          0
Smiles                 0
Functionality.1        0
Functionality 0        0
Functionality 1     1767
Functionality 2     2697
Functionality 3     3115
Functionality 4     3277
Functionality 5     3338
Functionality 6     3368
Functionality 7     3375
Functionality 8     3376
Functionality 9     3376
Functionality 10    3376
Functionality 11    3376
Functionality 12    3376
alias               3376
dtype: int64
(3376, 19)

/Users/zhouhanfeng/opt/anaconda3/envs/py38/lib/python3.8/site-packages/pandas/core/series.py:1056: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cacher_needs_updating = self._check_is_chained_assignment_possible()

Functionality          0
Canonical_smiles       0
Chemical Name          0
Smiles                 0
Functionality.1        0
Functionality 0        0
Functionality 1     1664
Functionality 2     2629
Functionality 3     3064
Functionality 4     3234
Functionality 5     3303
Functionality 6     3346
Functionality 7     3356
Functionality 8     3360
Functionality 9     3363
Functionality 10    3365
Functionality 11    3368
Functionality 12    3370
alias               3194
dtype: int64
(2962, 19)

In [13]:
print("Duplicate Count")
for col_name in df.columns:
    if not col_name.startswith("Func"):
        print(col_name, ":", df[col_name].duplicated(keep=False).sum())

Duplicate Count
Canonical_smiles : 0
Chemical Name : 173
Smiles : 0
alias : 2784

In [16]:
df[df.alias.isna() == False].alias

20                                      CI 20470/CI 50420
23                                               CI 42051
26                                               CI 42090
31                                               CI 73015
34                                               CI 61570
                              ...
3137    SODIUM TRIDECETH-8 CARBOXYLATE/SODIUM TRIDECET...
3237    STEARETH-13/STEARETH-14/STEARETH-15/STEARETH-1...
3447         TRIDECETH-6 PHOSPHATE/TRIDECETH-10 PHOSPHATE
3448    TRIDECETH-6/TRIDECETH-8/TRIDECETH-9/TRIDECETH-...
3610    AMMONIUM LAURETH-5 SULFATE/AMMONIUM LAURETH-7 ...
Name: alias, Length: 182, dtype: object